# Compare results

This notebook will show you the results of retrieval and generation evaluation.

In [1]:
generation_paths = ['./data/generation_eval_results_naive.csv', 
                    './data/generation_eval_results_em.csv',
                    './data/generation_eval_results_em_rr_k.csv',
                    './data/generation_eval_results_em_ch_rr_k.csv',
                    './data/generation_eval_results_em_ch_rr_k_mf.csv',
                    './data/generation_eval_results_em_ch_rr_k_hs.csv']

retrieval_paths = ['./data/retrieval_eval_results_naive.csv',
                   './data/retrieval_eval_results_em.csv',
                   './data/retrieval_eval_results_em_rr_k.csv',
                   './data/retrieval_eval_results_em_ch_rr_k.csv',
                   './data/retrieval_eval_results_em_ch_rr_k_mf.csv',
                   './data/retrieval_eval_results_em_ch_rr_k_hs.csv']

In [ ]:
import pandas as pd

generation_dfs = [pd.read_csv(path) for path in generation_paths]
retrieval_dfs = [pd.read_csv(path) for path in retrieval_paths]

generation_df = pd.concat(generation_dfs, ignore_index=True)
retrieval_df = pd.concat(retrieval_dfs, ignore_index=True)

In [5]:
retrieval_df

,retriever,hard_hit_rate,hard_mrr,hard_precision,hard_recall,hard_ap,hard_ndcg,soft_hit_rate,soft_precision,soft_recall,soft_mrr,soft_avg_retrieved_max_similarity,soft_avg_reference_max_similarity,soft_relevant_retrieved_count,soft_covered_reference_count
0,configured_rag,0.290456,0.228976,0.058091,0.290456,0.228976,0.244206,0.780083,0.341079,0.780083,0.708575,0.650019,0.867581,1.705394,0.780083
1,configured_rag,0.302905,0.266736,0.060581,0.302905,0.266736,0.275885,0.991701,0.858091,0.991701,0.957261,0.803547,0.920538,4.290456,0.991701
2,configured_rag,0.319502,0.292185,0.185685,0.319502,0.292185,0.299208,0.954357,0.924620,0.954357,0.941909,0.868149,0.911489,2.153527,0.954357
3,configured_rag,0.219917,0.194813,0.133126,0.219917,0.194813,0.201129,0.970954,0.929391,0.970954,0.961618,0.863332,0.907619,2.248963,0.970954
4,configured_rag,0.161826,0.138797,0.098479,0.161826,0.138797,0.144569,0.846473,0.803873,0.846473,0.841286,0.825862,0.861097,1.817427,0.846473
5,configured_rag,0.165975,0.154910,0.120401,0.165975,0.154910,0.157775,0.925311,0.884025,0.925311,0.917012,0.845898,0.880036,1.742739,0.925311

In [4]:
generation_df

,total_queries,faithfulness_avg_score,faithfulness_pass_rate,relevancy_avg_score,relevancy_pass_rate,correctness_avg_score,correctness_pass_rate,llm_judge_avg_score,semantic_similarity_avg_score,semantic_similarity_pass_rate
0,15,0.866667,0.866667,0.866667,0.866667,3.533333,0.533333,3.800000,0.782496,0.600000
1,15,0.866667,0.866667,0.933333,0.933333,4.200000,0.800000,4.400000,0.845929,0.666667
2,15,0.800000,0.800000,0.600000,0.600000,3.966667,0.666667,4.000000,0.851452,0.600000
3,15,1.000000,1.000000,0.800000,0.800000,3.966667,0.666667,4.266667,0.849698,0.733333
4,15,0.866667,0.866667,0.600000,0.600000,3.333333,0.466667,3.600000,0.811836,0.533333
5,15,1.000000,1.000000,0.800000,0.800000,3.800000,0.600000,4.133333,0.855246,0.733333